/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TaskLogin {
    }
}
declare global {
    interface HTMLTaskLoginElement extends Components.TaskLogin, HTMLStencilElement {
    }
    var HTMLTaskLoginElement: {
        prototype: HTMLTaskLoginElement;
        new (): HTMLTaskLoginElement;
    };
    interface HTMLElementTagNameMap {
        "task-login": HTMLTaskLoginElement;
    }
}
declare namespace LocalJSX {
    interface TaskLogin {
    }
    interface IntrinsicElements {
        "task-login": TaskLogin;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "task-login": LocalJSX.TaskLogin & JSXBase.HTMLAttributes<HTMLTaskLoginElement>;
        }
    }
}
